### PR TITLE
Update gui.py

### PR DESCRIPTION
**Pull request by Alexandra202421**
updated gui to default to f_i = 1425, f_f = 1415, 10 integrations at 5 seconds each

### CODE REVIEW

**Review by adampbeardsley — COMMENTED** [review]
Great! Could you also change the "placeholder text" so it's clear to the user?
Hint: to find all the places we've hard-coded a number like `1390`, you can just search the file for that number. Just be careful you're only changing things you mean to.
Another hint: Good programming practice would only have these numbers declared in one place... if you were feeling ambitious you could fix this, but not necessary for this PR.

**Comment by Alexandra202421** [comment]
for the gui.py file, the default parameters are input under the start function. If I had the start function return a list of numbers so I could reference them later in the code, would that still run okay?

**Comment by adampbeardsley** [comment]
hm, the problem is that I'm not sure where `start()` returns to, given it's called from one of the GUI buttons.
You may want to think about it the other way around... the first time the defaults are actually used is when the widgets are set up (e.g. lines 326-332 for the `freq_i` box). The `start()` function doesn't actually get run until the user clicks the button. So the default values need to be "known" from the time when the boxes are created, and `start()` needs to know what they were. You can probably do this with a global variable. I'm surprised you can't set a "default" value in the `CTkEntry()` class, but I haven't been able to find it by googling.

**Comment by Alexandra202421** [comment]
Ahhh okay I get it, I set up a new variable under the default parameters function that sets the values and then just referenced them everywhere else. So if someone wants to change it later its all in one place

**Comment by Alexandra202421** [comment]
I think I've fixed the default parameters! I made 4 new values for the parameters about halfway down and reference them inside the start function so they should be able to easily be changed later

**Comment by adampbeardsley** [comment]
Great! Just don't forget to push your new changes, and either test things out on your end or I can test it on my side. 

When you push the changes, it will automatically become part of this PR (assuming you're still working on the same branch), so no need to make a new one.

**Comment by Alexandra202421** [comment]
The gui opened up on my computer and displayed correctly so I think its good to go!

**Comment by adampbeardsley** [comment]
Great @Alexandra202421 , just don't forget you need to push your latest change for it to show up here. Right now I only see the original commit where you made the change in one place.

**Comment by Alexandra202421** [comment]
I think I did it? I just tried again just in case

**Review by adampbeardsley — APPROVED** [review]
Looks good. I just made a couple quick fixes:
- The default parameters were defined twice, I removed one of them
- They needed to be strings rather than ints so they get concatenated to the data collection command properly.

**Pull request merged**
